var _____bible =
{
   __books:
      [
         "Ge",
         "Exo",
         "Lev",
         "Num",
         "Deu",
         "Josh",
         "Jdgs",
         "Ruth",
         "1Sm",
         "2Sm",
         "1Ki",
         "2Ki",
         "1Chr",
         "2Chr",
         "Ezra",
         "Neh",
         "Est",
         "Job",
         "Psa",
         "Prv",
         "Eccl",
         "SSol",
         "Isa",
         "Jer",
         "Lam",
         "Eze",
         "Dan",
         "Hos",
         "Joel",
         "Amos",
         "Obad",
         "Jonah",
         "Mic",
         "Nahum",
         "Hab",
         "Zep",
         "Hag",
         "Zec",
         "Mal",
         "Mat",
         "Mark",
         "Luke",
         "John",
         "Acts",
         "Rom",
         "1Cor",
         "2Cor",
         "Gal",
         "Eph",
         "Phi",
         "Col",
         "1Th",
         "2Th",
         "1Tim",
         "2Tim",
         "Titus",
         "Phmn",
         "Heb",
         "Jas",
         "1Pet",
         "2Pet",
         "1Jn",
         "2Jn",
         "3Jn",
         "Jude",
         "Rev"
      ],

   books:
   {
      "Ge": "Genesis",
      "Exo": "Exodus",
      "Lev": "Leviticus",
      "Num": "Numbers",
      "Deu": "Deuteronomy",
      "Josh": "Joshua",
      "Jdgs": "Judges",
      "Ruth": "Ruth",
      "1Sm": "1 Samuel",
      "2Sm": "2 Samuel",
      "1Ki": "1 Kings",
      "2Ki": "2 Kings",
      "1Chr": "1 Chronicles",
      "2Chr": "2 Chronicles",
      "Ezra": "Ezra",
      "Neh": "Nehemiah",
      "Est": "Esther",
      "Job": "Job",
      "Psa": "Psalm", // NB: Psalm not Psalms
      "Prv": "Proverbs",
      "Eccl": "Ecclesiastes",
      "SSol": "Song of Solomon",
      "Isa": "Isaiah",
      "Jer": "Jeremiah",
      "Lam": "Lamentations",
      "Eze": "Ezekiel",
      "Dan": "Daniel",
      "Hos": "Hosea",
      "Joel": "Joel",
      "Amos": "Amos",
      "Obad": "Obadiah",
      "Jonah": "Jonah",
      "Mic": "Micah",
      "Nahum": "Nahum",
      "Hab": "Habakkuk",
      "Zep": "Zephaniah",
      "Hag": "Haggai",
      "Zec": "Zechariah",
      "Mal": "Malachi",
      "Mat": "Matthew",
      "Mark": "Mark",
      "Luke": "Luke",
      "John": "John",
      "Acts": "Acts",
      "Rom": "Romans",
      "1Cor": "1 Corinthians",
      "2Cor": "2 Corinthians",
      "Gal": "Galatians",
      "Eph": "Ephesians",
      "Phi": "Philippians",
      "Col": "Colossians",
      "1Th": "1 Thessalonians",
      "2Th": "2 Thessalonians",
      "1Tim": "1 Timothy",
      "2Tim": "2 Timothy",
      "Titus": "Titus",
      "Phmn": "Philemon",
      "Heb": "Hebrews",
      "Jas": "James",
      "1Pet": "1 Peter",
      "2Pet": "2 Peter",
      "1Jn": "1 John",
      "2Jn": "2 John",
      "3Jn": "3 John",
      "Jude": "Jude",
      "Rev": "Revelation"
   },

   booksCritical:
   {
      "Ge": "Ge",
      "Exo": "Ex",
      "Lev": "Le",
      "Num": "Nu",
      "Deu": "De",
      "Josh": "Jos",
      "Jdgs": "Jud",
      "Ruth": "Ru",
      "1Sm": "1Sa",
      "2Sm": "2Sa",
      "1Ki": "1Ki",
      "2Ki": "2Ki",
      "1Chr": "1Ch",
      "2Chr": "2Ch",
      "Ezra": "Ezr",
      "Neh": "Ne",
      "Est": "Es",
      "Job": "Job",
      "Psa": "Ps",
      "Prv": "Pr",
      "Eccl": "Ec",
      "SSol": "So",
      "Isa": "Isa",
      "Jer": "Jer",
      "Lam": "La",
      "Eze": "Eze",
      "Dan": "Da",
      "Hos": "Ho",
      "Joel": "Joe",
      "Amos": "Am",
      "Obad": "Ob",
      "Jonah": "Jon",
      "Mic": "Mic",
      "Nahum": "Na",
      "Hab": "Hab",
      "Zep": "Zep",
      "Hag": "Hag",
      "Zec": "Zec",
      "Mal": "Mal",
      "Mat": "Mt",
      "Mark": "Mr",
      "Luke": "Lu",
      "John": "Joh",
      "Acts": "Ac",
      "Rom": "Ro",
      "1Cor": "1Co",
      "2Cor": "2Co",
      "Gal": "Ga",
      "Eph": "Eph",
      "Phi": "Php",
      "Col": "Col",
      "1Th": "1Th",
      "2Th": "2Th",
      "1Tim": "1Ti",
      "2Tim": "2Ti",
      "Titus": "Tit",
      "Phmn": "Phm",
      "Heb": "Heb",
      "Jas": "Jas",
      "1Pet": "1Pe",
      "2Pet": "2Pe",
      "1Jn": "1Jo",
      "2Jn": "2Jo",
      "3Jn": "3Jo",
      "Jude": "Jude",
      "Rev": "Re"
   },

   chapterCount:
   {
      "Ge": 50,
      "Exo": 40,
      "Lev": 27,
      "Num": 36,
      "Deu": 34,
      "Josh": 24,
      "Jdgs": 21,
      "Ruth": 4,
      "1Sm": 31,
      "2Sm": 24,
      "1Ki": 22,
      "2Ki": 25,
      "1Chr": 29,
      "2Chr": 36,
      "Ezra": 10,
      "Neh": 13,
      "Est": 10,
      "Job": 42,
      "Psa": 150,
      "Prv": 31,
      "Eccl": 12,
      "SSol": 8,
      "Isa": 66,
      "Jer": 52,
      "Lam": 5,
      "Eze": 48,
      "Dan": 12,
      "Hos": 14,
      "Joel": 3,
      "Amos": 9,
      "Obad": 1,
      "Jonah": 4,
      "Mic": 7,
      "Nahum": 3,
      "Hab": 3,
      "Zep": 3,
      "Hag": 2,
      "Zec": 14,
      "Mal": 4,
      "Mat": 28,
      "Mark": 16,
      "Luke": 24,
      "John": 21,
      "Acts": 28,
      "Rom": 16,
      "1Cor": 16,
      "2Cor": 13,
      "Gal": 6,
      "Eph": 6,
      "Phi": 4,
      "Col": 4,
      "1Th": 5,
      "2Th": 3,
      "1Tim": 6,
      "2Tim": 4,
      "Titus": 3,
      "Phmn": 1,
      "Heb": 13,
      "Jas": 5,
      "1Pet": 5,
      "2Pet": 3,
      "1Jn": 5,
      "2Jn": 1,
      "3Jn": 1,
      "Jude": 1,
      "Rev": 22
   },

   bookSearch:
   [
      ["Ge", "Genesis", "Gen"],
      ["Exo", "Exodus", "Ex", "Exod"],
      ["Lev", "Leviticus", "Le"],
      ["Num", "Numbers", "Nu", "Numb"],
      ["Deu", "Deuteronomy", "De", "Deut"],
      ["Josh", "Joshua", "Jos"],
      ["Jdgs", "Judges", "Judg"],
      ["Ruth", "Ruth", "Ru"],
      ["1Sm", "1 Samuel", "1 Sa", "1 Sam", "1 Sm", "1 S", "1Samuel", "1Sa", "1Sam", "1S"],
      ["2Sm", "2 Samuel", "2 Sa", "2 Sam", "2 Sm", "2 S", "2Samuel", "2Sa", "2Sam", "2S"],
      ["1Ki", "1 Kings", "1Kings", "1 Ki", "1 Kin", "1 King", "1Kin", "1King", "1 K", "1K"],
      ["2Ki", "2 Kings", "2Kings", "2 Ki", "2 Kin", "2 King", "2Kin", "2King", "2 K", "2K"],
      ["1Chr", "1 Chronicles", "1 Ch", "1Chronicles", "1Ch", "1 Chr", "1 Chron", "1Chron"],
      ["2Chr", "2 Chronicles", "2 Ch", "2Chronicles", "2Ch", "2 Chr", "2 Chron", "2Chron"],
      ["Ezra", "Ezra", "Ezr"],
      ["Neh", "Nehemiah", "Ne"],
      ["Est", "Esther", "Es", "Esth"],
      ["Job", "Job"],
      ["Psa", "Psalms", "Ps", "Psalm"],
      ["Prv", "Proverbs", "Pro", "Pr", "Prov", "Proverb"],
      ["Eccl", "Ecclesiastes", "Ec", "Ecc", "Eccles"],
      ["SSol", "Song of Solomon", "Song", "SOS", "So"],
      ["Isa", "Isaiah", "Is", "I"],
      ["Jer", "Jeremiah", "Je"],
      ["Lam", "Lamentations", "La"],
      ["Eze", "Ezekiel", "Ezek"],
      ["Dan", "Daniel", "Da"],
      ["Hos", "Hosea", "Ho"],
      ["Joel", "Joel", "Joe"],
      ["Amos", "Amos", "Amo", "Am"],
      ["Obad", "Obadiah", "Oba", "Ob", "O"],
      ["Jonah", "Jonah", "Jon"],
      ["Mic", "Micah", "Mi"],
      ["Nahum", "Nahum", "Nah", "Na"],
      ["Hab", "Habakkuk", "Habak"],
      ["Zep", "Zephaniah", "Zeph"],
      ["Hag", "Haggai"],
      ["Zec", "Zechariah", "Zech"],
      ["Mal", "Malachi"],
      ["Mat", "Matthew", "Matt"],
      ["Mark", "Mark", "Mar"],
      ["Luke", "Luke", "Lu"],
      ["John", "John", "Joh"],
      ["Acts", "Acts", "Act", "Ac"],
      ["Rom", "Romans", "Ro"],
      ["1Cor", "1 Corinthians", "1Corinthians", "1 Co", "1Co", "1 Cor"],
      ["2Cor", "2 Corinthians", "2Corinthians", "2 Co", "2Co", "2 Cor"],
      ["Gal", "Galatians", "Ga"],
      ["Eph", "Ephesians", "Ep"],
      ["Phi", "Philippians", "Phili", "Philip"],
      ["Col", "Colossians", "Co"],
      ["1Th", "1 Thessalonians", "1Thessalonians", "1 Th", "1 Thes", "1 Thess", "1Thes", "1Thess"],
      ["2Th", "2 Thessalonians", "2Thessalonians", "2 Th", "2 Thes", "2 Thess", "2Thes", "2Thess"],
      ["1Tim", "1 Timothy", "1Timothy", "1 Tim", "1Ti", "1 Ti"],
      ["2Tim", "2 Timothy", "2Timothy", "2 Tim", "2Ti", "2 Ti"],
      ["Titus", "Titus", "Tit"],
      ["Phmn", "Philemon", "Phile"],
      ["Heb", "Hebrews", "He"],
      ["Jas", "James", "Jam", "Ja"],
      ["1Pet", "1 Peter", "1 Pet", "1P", "1 P", "1Pe", "1 Pe"],
      ["2Pet", "2 Peter", "2 Pet", "2P", "2 P", "2Pe", "2 Pe"],
      ["1Jn", "1 John", "1John", "1 Jn", "1 Joh", "1Joh", "1 J", "1J"],
      ["2Jn", "2 John", "2John", "2 Jn", "2 Joh", "2Joh", "2 J", "2J"],
      ["3Jn", "3 John", "3John", "3 Jn", "3 Joh", "3Joh", "3 J", "3J"],
      ["Jude", "Jude"],
      ["Rev", "Revelation", "Re"]
   ],

   ambiguous:
   [
      /* Allow these exceptions...
      "Ge",
      "Le",
      "De",
      "Ne",
      "Es",
      "Ec",
      "Is",
      "La",
      "Ob",
      "Nah",
      "Joh",
      ... */
      "Co", // Matches 1 Corinthians, 2 Corinthians and Colossians
      "Phi" // Matches Philippians and Philemon
   ],

   __version: // This is now INEFFECTIVE at updating offline books - refer to offline.js MQUPDATE
   {
      "Ge": "20170922_1034",
      "Exo": "20170922_1211",
      "Lev": 1,
      "Num": "20230320_1100",
      "Deu": 1,
      "Josh": 1,
      "Jdgs": 1,
      "Ruth": 1,
      "1Sm": 1,
      "2Sm": 1,
      "1Ki": 1,
      "2Ki": 1,
      "1Chr": 1,
      "2Chr": 1,
      "Ezra": 1,
      "Neh": 1,
      "Est": 1,
      "Job": 1,
      "Psa": "20190502_1625",
      "Prv": 1,
      "Eccl": 1,
      "SSol": 1,
      "Isa": 1,
      "Jer": 1,
      "Lam": 1,
      "Eze": 1,
      "Dan": 1,
      "Hos": 1,
      "Joel": 1,
      "Amos": 1,
      "Obad": 1,
      "Jonah": 1,
      "Mic": 1,
      "Nahum": 1,
      "Hab": 1,
      "Zep": 1,
      "Hag": 1,
      "Zec": 1,
      "Mal": 1,
      "Mat": "20151026_1141",
      "Mark": 1,
      "Luke": 1,
      "John": "20151028_1201",
      "Acts": "20170102_1314",
      "Rom": 1,
      "1Cor": 1,
      "2Cor": 1,
      "Gal": 1,
      "Eph": 1,
      "Phi": 1,
      "Col": 1,
      "1Th": 1,
      "2Th": 1,
      "1Tim": 1,
      "2Tim": 1,
      "Titus": 1,
      "Phmn": 1,
      "Heb": 1,
      "Jas": 1,
      "1Pet": 1,
      "2Pet": 1,
      "1Jn": 1,
      "2Jn": 1,
      "3Jn": 1,
      "Jude": 1,
      "Rev": "20190518_1144"
   },

   groups:
   {
      "Ge": "Moses' Law[0]",
      "Josh": "Jewish History[1]",
      "Job": "Poetry Wisdom[2]",
      "Isa": "Major Prophets[3]",
      "Hos": "Minor Prophets[4]",
      "Mat": "Jesus' Life[5]",
      "Acts": "First Century[6]",
      "Rom": "Paul's Letters[7]",
      "Jas": "Other Letters[8]",
      "Rev": "Last Days[9]"
      /*"Ge": "Moses' Law &bull; Gen to Deu",
      "Josh": "Jewish History &bull; Josh to Est",
      "Job": "Poetry Wisdom &bull; Job to Song",
      "Isa": "Major Prophets &bull; Isa to Dan",
      "Hos": "Minor Prophets &bull; Hos to Mal",
      "Mat": "Jesus' Life &bull; Mat to John",
      "Acts": "First Century &bull; Acts",
      "Rom": "Paul's Letters &bull; Rom to Heb",
      "Jas": "Other Letters &bull; Jas to Jude",
      "Rev": "Last Days &bull; Rev"*/
   },

   verses: [],
   versesFlat: [],
   //versesAudioScript: [],
   quotes: []
};